{
    'name': 'School Management',
    'version': '1.0',
    'summary': 'Module for managing schools',
    'sequence': 10,
    'description': """School Management System""",
    'category': 'Education',
    'author': 'Tran Huu Hau',
    'website': 'http://www.example.com',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/classroom_views.xml',
        'views/timetable_views.xml',
        'views/student_views.xml',
        'views/parent_views.xml',
        'views/subject_views.xml',
        'views/attendance_views.xml',
        'views/exam_result_views.xml',
        'views/fee_views.xml',
        'views/student_sequence.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
